#!/usr/bin/env Rscript
### Fixture tests for the 2n cohort policy resolution
### (compile_cohort_annotations_2n) and rule-13 best-fit resolution
### (update_best_fit_status_2n), using purely synthetic sample trees.
###
### Run: Rscript tests/test_compile_cohort_annotations_2n.R
### Exits non-zero on the first failure.
###
### Covers the spec's "where the two cohorts diverge" table plus the explicit
### fit_to_use path. No package install needed -- sources the R/ files directly.

suppressPackageStartupMessages({
  suppressWarnings({
    library(data.table)
    library(plyr)
    library(dplyr)
    library(tidyr)
    library(purrr)
    library(tibble)
    library(parallel)
    library(R.utils)
  })
})

repo <- normalizePath(file.path(dirname(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)[1])), ".."))
suppressWarnings(suppressMessages({
  source(file.path(repo, "R", "global.R"))      # get_review_status, verify_access_to_write, ...
  source(file.path(repo, "R", "global_2n.R"))
  source(file.path(repo, "R", "compile_cohort_annotations_2n.R"))
}))

AUTOQC <- autoqc_reviewer_id_2n()
HUMAN  <- "reviewer_a"
HUMAN2 <- "reviewer_b"

n_pass <- 0; n_fail <- 0
check <- function(label, cond) {
  if (isTRUE(cond)) { n_pass <<- n_pass + 1; cat("PASS:", label, "\n") }
  else { n_fail <<- n_fail + 1; cat("FAIL:", label, "\n") }
}

## ---- fixture builders (synthetic ids only; no patient data) ----

qc_row <- function(fit_name) {
  data.frame(tumor_sample_id = "T_SYNTH_N_SYNTH", fit_name = fit_name,
             purity_run_Purity = 0.5, purity_run_Ploidy = 2.1,
             hisens_run_Purity = 0.4, hisens_run_Ploidy = 2.0,
             is_best_fit = FALSE, facets_qc = TRUE,
             facets_qc_version = "1.0", facets_suite_version = "3.0.0",
             stringsAsFactors = FALSE)
}

manifest_row <- function(sample_path, review_status, fit_name, reviewed_by,
                         date_reviewed, reviewer_set_purity = NA,
                         use_only_purity_run = FALSE) {
  data.frame(sample = "T_SYNTH_N_SYNTH", path = paste0(sample_path, "/"),
             review_status = review_status, fit_name = fit_name,
             review_notes = NA, reviewed_by = reviewed_by,
             date_reviewed = date_reviewed, facets_qc = TRUE,
             use_only_purity_run = use_only_purity_run, use_edited_cncf = FALSE,
             reviewer_set_purity = reviewer_set_purity,
             facets_qc_version = "1.0", facets_suite_version = "3.0.0",
             stringsAsFactors = FALSE)
}

make_sample <- function(fits, manifest_rows) {
  d <- file.path(tempfile("fx2n_"))
  dir.create(d, recursive = TRUE)
  for (f in fits) dir.create(file.path(d, f), recursive = TRUE, showWarnings = FALSE)
  qc <- do.call(rbind, lapply(fits, qc_row))
  write.table(qc, file.path(d, "facets_qc.txt"), quote = FALSE, row.names = FALSE, sep = "\t")
  mf <- file.path(d, "facets_review.manifest")
  writeLines("# generated by facets-preview app. DO NOT EDIT.", mf)
  suppressWarnings(write.table(do.call(rbind, manifest_rows), mf, append = TRUE,
                               sep = "\t", row.names = FALSE, quote = FALSE))
  d
}

not_reviewed <- function(d, fit) manifest_row(d, "not_reviewed", fit, NA, NA)

run_policy <- function(sample_path, policy, fit_to_use = NA) {
  out_prefix <- file.path(tempfile("out2n_"))
  dir.create(dirname(out_prefix), recursive = TRUE, showWarnings = FALSE)
  res <- suppressWarnings(compile_cohort_annotations_2n(
    data.frame(sample_id = "T_SYNTH_N_SYNTH", sample_path = sample_path,
               fit_to_use = fit_to_use, stringsAsFactors = FALSE),
    out_prefix, ncores = 1, policy = policy))
  res
}

## ---- case 1: human best A, autoQC best B -> autoqc: B, ruleset: A ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(d0 <- ".", "reviewed_best_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-02 10:00:00", reviewer_set_purity = "0.77"),
  manifest_row(".", "auto_qc_best_fit", "default", AUTOQC, "2026-01-03 10:00:00"),
  manifest_row(".", "auto_qc_pass", "alt_dipLogR_-0.2", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case1 autoqc picks autoQC's fit",      r_a$fit_name[1] == "default")
check("case1 autoqc review row is autoQC's",  r_a$reviewed_by[1] == AUTOQC)
check("case1 ruleset picks human's fit",      r_r$fit_name[1] == "alt_dipLogR_-0.2")
check("case1 ruleset review row is human's",  r_r$reviewed_by[1] == HUMAN)
check("case1 ruleset purity from human row",  r_r$purity[1] == "0.77")

## ---- case 2: human best A, autoQC best A -> same fit, different purity source ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_best_fit", "default", HUMAN, "2026-01-02 10:00:00", reviewer_set_purity = "0.66"),
  manifest_row(".", "auto_qc_best_fit", "default", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case2 same fit both policies", r_a$fit_name[1] == "default" && r_r$fit_name[1] == "default")
check("case2 autoqc purity NOT borrowed from human", r_a$purity[1] != "0.66")
check("case2 ruleset purity from human row",         r_r$purity[1] == "0.66")
check("case2 provenance differs", r_a$reviewed_by[1] == AUTOQC && r_r$reviewed_by[1] == HUMAN)

## ---- case 3: human no fit, autoQC best A -> both A ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_no_fit", "Not selected", HUMAN, "2026-01-02 10:00:00"),
  manifest_row(".", "auto_qc_best_fit", "alt_dipLogR_-0.2", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case3 both policies pick autoQC's fit",
      r_a$fit_name[1] == "alt_dipLogR_-0.2" && r_r$fit_name[1] == "alt_dipLogR_-0.2")

## ---- case 4: human best A, autoQC no fit -> autoqc: default+NA fields, ruleset: A ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_best_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-02 10:00:00", reviewer_set_purity = "0.55"),
  manifest_row(".", "auto_qc_no_fit", "Not selected", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case4 autoqc falls back to default",   r_a$fit_name[1] == "default")
check("case4 autoqc review fields all NA",    is.na(r_a$reviewed_by[1]) && is.na(r_a$review_status[1]) && is.na(r_a$reviewer_set_purity[1]))
check("case4 autoqc purity NOT human's 0.55", is.na(r_a$purity[1]) || r_a$purity[1] != "0.55")
check("case4 ruleset picks human's fit",      r_r$fit_name[1] == "alt_dipLogR_-0.2")

## ---- case 5: human acceptable A, autoQC no fit -> autoqc: default, ruleset: A (tier 3) ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_acceptable_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-02 10:00:00"),
  manifest_row(".", "auto_qc_no_fit", "Not selected", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case5 autoqc falls back to default",  r_a$fit_name[1] == "default")
check("case5 ruleset tier3 acceptable fit",  r_r$fit_name[1] == "alt_dipLogR_-0.2")

## ---- case 5b: two acceptable fits -> most recent date_reviewed wins tier 3 ----
d <- make_sample(c("default", "alt_dipLogR_-0.2", "alt_dipLogR_-0.4"), list(
  manifest_row(".", "reviewed_acceptable_fit", "alt_dipLogR_-0.4", HUMAN,  "2026-01-01 10:00:00"),
  manifest_row(".", "reviewed_acceptable_fit", "alt_dipLogR_-0.2", HUMAN2, "2026-01-05 10:00:00")))
r_r <- run_policy(d, "ruleset")
check("case5b tier3 most recent acceptable wins", r_r$fit_name[1] == "alt_dipLogR_-0.2")

## ---- case 6: nobody reviewed, autoQC best A -> both A ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  not_reviewed(".", "default"),
  manifest_row(".", "auto_qc_best_fit", "alt_dipLogR_-0.2", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case6 both pick autoQC's fit",
      r_a$fit_name[1] == "alt_dipLogR_-0.2" && r_r$fit_name[1] == "alt_dipLogR_-0.2")

## ---- case 7: nobody reviewed, autoQC no fit -> both default, NA fields ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  not_reviewed(".", "default"),
  manifest_row(".", "auto_qc_no_fit", "Not selected", AUTOQC, "2026-01-03 10:00:00")))
r_a <- run_policy(d, "autoqc"); r_r <- run_policy(d, "ruleset")
check("case7 both fall to default", r_a$fit_name[1] == "default" && r_r$fit_name[1] == "default")
check("case7 ruleset review fields NA", is.na(r_r$reviewed_by[1]))

## ---- case 8: verdict on an ultra fit is never selectable ----
d <- make_sample(c("default", "default/ultra"), list(
  not_reviewed(".", "default"),
  manifest_row(".", "reviewed_best_fit", "default/ultra", HUMAN, "2026-01-02 10:00:00")))
r_r <- run_policy(d, "ruleset")
check("case8 ultra never selectable -> default", r_r$fit_name[1] == "default")

## ---- case 9: explicit fit_to_use -> uniform frame + review join applied ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_best_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-02 10:00:00", reviewer_set_purity = "0.88"),
  manifest_row(".", "auto_qc_best_fit", "default", AUTOQC, "2026-01-03 10:00:00")))
r_x <- run_policy(d, "ruleset", fit_to_use = "alt_dipLogR_-0.2")
check("case9 explicit fit honored",         r_x$fit_name[1] == "alt_dipLogR_-0.2")
check("case9 review join applied (purity)", r_x$purity[1] == "0.88")
check("case9 uniform frame has purity col", "purity" %in% names(r_x))

## ---- rule 13: update_best_fit_status_2n ----
d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_best_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-02 10:00:00"),
  manifest_row(".", "auto_qc_best_fit", "default", AUTOQC, "2026-01-03 10:00:00")))
update_best_fit_status_2n("T_SYNTH_N_SYNTH", d)
qc <- fread(file.path(d, "facets_qc.txt"))
check("rule13 human best wins is_best_fit despite older date",
      qc[fit_name == "alt_dipLogR_-0.2"]$is_best_fit == TRUE && qc[fit_name == "default"]$is_best_fit == FALSE)
check("rule13 rewrite preserves version string as 1.0",
      as.character(fread(file.path(d, "facets_qc.txt"),
                         colClasses = list(character = "facets_qc_version"))$facets_qc_version[1]) == "1.0")

d <- make_sample(c("default", "alt_dipLogR_-0.2"), list(
  manifest_row(".", "reviewed_acceptable_fit", "alt_dipLogR_-0.2", HUMAN, "2026-01-05 10:00:00"),
  manifest_row(".", "auto_qc_best_fit", "default", AUTOQC, "2026-01-03 10:00:00")))
update_best_fit_status_2n("T_SYNTH_N_SYNTH", d)
qc <- fread(file.path(d, "facets_qc.txt"))
check("rule13 autoQC best beats newer human acceptable",
      qc[fit_name == "default"]$is_best_fit == TRUE)

d <- make_sample(c("default"), list(
  manifest_row(".", "auto_qc_no_fit", "Not selected", AUTOQC, "2026-01-03 10:00:00"),
  not_reviewed(".", "default")))
update_best_fit_status_2n("T_SYNTH_N_SYNTH", d)
qc <- fread(file.path(d, "facets_qc.txt"))
check("rule13 no best -> nothing marked", all(qc$is_best_fit == FALSE))

cat("\n", n_pass, "passed,", n_fail, "failed\n")
quit(status = ifelse(n_fail > 0, 1, 0))
